module.exports.CONTENT_DATA = [
    // {
    //     concept: "Hello Welcome",
    //     conceptImg: "/static/media/ideas.808127d1.png",
    //     createdAt: "2021:8:15",
    //     description: "Edit description here",
    //     id: "ws11ef472dbf205f00",
    //     parent: undefined,
    //     title: "Work space1",
    //     type: "site",
    // },
    // {
    //     concept: "Hello Welcome",
    //     conceptImg: "/static/media/ideas.808127d1.png",
    //     createdAt: "2021:8:15",
    //     description: "Edit description here",
    //     id: "ws11ef472dbf205f11",
    //     parent: undefined,
    //     title: "Work space2",
    //     type: "site",
    // },
    // {
    //     concept: "Hello Welcome",
    //     conceptImg: "/static/media/ideas.808127d1.png",
    //     createdAt: "2021:8:15",
    //     description: "Edit description here",
    //     id: "wse55114ada191500",
    //     parent: undefined,
    //     title: "Work space3",
    //     type: "site",
    // },
    // {
    //     createdAt: undefined,
    //     description: undefined,
    //     id: "block904e28cb57f4100",
    //     parent: "wse55114ada191500",
    //     subType: "full",
    //     title: undefined,
    //     type: "block",
    // },
    // {
    //     createdAt: undefined,
    //     description: undefined,
    //     id: "full904e28cb57f4100",
    //     parent: "block904e28cb57f4100",
    //     title: "Topic Name",
    //     type: "topic",
    // },
    // {
    //     concept: "Hello Welcome",
    //     conceptImg: "/static/media/ideas.808127d1.png",
    //     createdAt: "2021:8:15",
    //     description: "Edit description here",
    //     id: "ws16d07d7bf30e2200",
    //     parent: undefined,
    //     title: "Work space",
    //     type: "site",
    // },
    // {
    //     createdAt: undefined,
    //     description: undefined,
    //     id: "blockbe84d31224cd700",
    //     parent: "ws16d07d7bf30e2200",
    //     subType: "split",
    //     title: undefined,
    //     type: "block",
    // },
    // {
    //     createdAt: undefined,
    //     description: undefined,
    //     id: "splitaf432910b1e7780",
    //     parent: "blockbe84d31224cd700",
    //     title: "Topic Name",
    //     type: "topic",
    // },
    // {
    //     createdAt: undefined,
    //     description: undefined,
    //     id: "split2e9d461f00afd20",
    //     parent: "blockbe84d31224cd700",
    //     title: "Topic Name",
    //     type: "topic",
    // },
]